// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TpProg2.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Sexo { get; set; }

    public string Dni { get; set; }

    public string Telefono { get; set; }

    public DateOnly? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }

    [JsonIgnore]
    public virtual ICollection<Mascota> Mascota { get; set; } = new List<Mascota>();
}