// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TpProg2.Models;

public partial class Especie
{
    public int IdEspecie { get; set; }

    public string NombreEspecie { get; set; }

    [JsonIgnore]
    public virtual ICollection<Mascota> Mascota { get; set; } = new List<Mascota>();
}