// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TpProg2.Models;

public partial class Mascota
{
    public int IdMascota { get; set; }

    public string Nombre { get; set; }

    public int IdEspecie { get; set; }

    public string Sexo { get; set; }

    public int? Anionacimiento { get; set; }

    public int IdCliente { get; set; }

    public DateOnly? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }

    [JsonIgnore]
    public virtual Cliente IdClienteNavigation { get; set; }

    [JsonIgnore]
    public virtual Especie IdEspecieNavigation { get; set; }
}